export const END_ROUND = 'END_ROUND'
export const START_ROUND = 'START_ROUND'
export const START_INITTING_GAME = 'START_INITTING_GAME'
export const SET_LEVEL = 'SET_LEVEL'
export const INIT_STATE = 'INIT_STATE'