export default [
  {
    imgName: 'monster-1',
    imgWidth: 384,
    imgHeight: 336,
    x: 1200,
    y: 455,
    rowHeight: 67,
    oneSpriteWidth: 48,
    oneSpriteHeight: 47.5,
    standingRowNum: 0,
    standingRowLength: 8,
    movingToHeroRowNum: 1,
    movingToHeroRowLength: 8,
    atackingHeroRowNum: 2,
    atackingHeroRowLength: 8,
    dyingHeroRowNum: 4,
    dyingHeroRowLength: 7,
    scale: 400
  },
  {
    imgName: 'monster-2',
    imgWidth: 1024,
    imgHeigh: 1913,
    x: 1100,
    y: 480,
    rowHeight: 95.65,
    oneSpriteWidth: 96,
    oneSpriteHeight: 95.65,
    standingRowNum: 17,
    standingRowLength: 3,
    movingToHeroRowNum: 12,
    movingToHeroRowLength: 5,
    atackingHeroRowNum: 16,
    atackingHeroRowLength: 4,
    dyingHeroRowNum: 19,
    dyingHeroRowLength: 6,
    scale: 500
  },
  {
    imgName: 'monster-3',
    imgWidth: 384,
    imgHeight: 336,
    x: 1200,
    y: 455,
    rowHeight: 67,
    oneSpriteWidth: 48,
    oneSpriteHeight: 47.5,
    standingRowNum: 0,
    standingRowLength: 8,
    movingToHeroRowNum: 1,
    movingToHeroRowLength: 8,
    atackingHeroRowNum: 2,
    atackingHeroRowLength: 8,
    dyingHeroRowNum: 4,
    dyingHeroRowLength: 7,
    scale: 400
  }
]
